apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gordminedisk2
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: minecraftgdd
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: minecraftgd
    spec:
      containers:
      - name: minecraftpersistg
        image: openhack/minecraft-server
        ports:
        - containerPort: 25565
        env:
        - name: EULA
          value: "TRUE"
        volumeMounts:
        - mountPath: "/data"
          name: volume
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: gordminedisk2
---
apiVersion: v1
kind: Service
metadata:
  name: minecraftgd
spec:
  type: LoadBalancer
  ports:
  ports:
  - port: 25565
    targetPort: 25565
    protocol: TCP
    name: mine
  - port: 25575
    targetPort: 25575
    protocol: TCP
    name: rcon
  selector:
    app: minecraftgd    
