kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: cluster-net-policy
spec:
  podSelector:
    matchLabels:
      app: azure-vote-front
      role: frontend
  ingress:
    - from:
      - podSelector:
          matchLabels: {}
